### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by chr1x2** [YosfanEilay/AuthLogParser#2]
It will be great if this tool can run on Linux (Ubuntu and Redhat-based)

**Comment by YosfanEilay** [comment]
Hi @chr1x2 
Thank you for your suggestion, 
You can install PowerShell on Linux and use this tool, but I would not suggest using this tool on Linux,
This tool is for after the data collecting on your IR case, and then to "Analyze at home" on your Windows machine.

Maybe in the future I will add the ability to run the tool on Linux without installing PowerShell
