### ISSUE TITLE
Unsupported logs

### ISSUE THREAD

**Issue by devkos120** [YosfanEilay/AuthLogParser#4]
When using MasterParser on the logs produced by the Zentyal server, I get these log files as unsupported logs. I am attaching a file with the first lines of the syslog. 
[syslog-01.log](https://github.com/securityjoes/MasterParser/files/15212434/syslog-01.log)

**Comment by YosfanEilay** [comment]
Hello @devkos120,
As of right now we don't have support for Zentyal OS, but is see that the syslog.log file is built with the same format RFC 3164
as the auth.log file from ubuntu, until we will have support for Zentyal OS you can just change the file name from syslog-01.log to auth.log-01.log and put the file in the Log folder in the MasterParser and this will work, if you have any question let me know ^_^

**Comment by YosfanEilay** [comment]
@devkos120  Will keep this issue open for now just to hear if this worked for you  :)

**Comment by YosfanEilay** [comment]
Was it working for you ? @devkos120

**Comment by YosfanEilay** [comment]
@devkos120 did not answer yet, closing this issue for now.
