### ISSUE TITLE
Log format request

### ISSUE THREAD

**Issue by Amras2322** [YosfanEilay/AuthLogParser#7]
Hello! Unsure if this is still active, but I saw an open invitation to submit log format requests.

Requesting support for Alerts.log and Audit.log

**Comment by Amras2322** [comment]
Upon further research it has come to my attention that these are not standard/common .log files. Disregard.

**Comment by YosfanEilay** [comment]
Hi @Amras2322 ! Thanks for your request and for your research result you shared with me, if you need any help let me know!
Have a wonderful rest of the day

**Comment by Amras2322** [comment]
Hey @YosfanEilay,

If you have the desire to look into this anyways, the files mentioned are created by Suricata (alerts.log) and auditd (audit.log)

**Comment by YosfanEilay** [comment]
@Amras2322 Send me some test logs files to my email regarding suricata.io logs, tell me there what you want to be able to pars, and ill try my best when I have time.

eilay@securityjoes.com
